# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0be2143bcbd11d1fc1dd7ca434efb1c9a79042874889e3a5dd38b514e848174212ff313692a4f2358f5ed449ba372c76d1570539d7714e38335c516766ea1792

test:
  secret_key_base: 7d727ad5d2a635eefa2175f23bafcaa604e0d33994b1c89ee619139c824ad36df32d58f07125dcd390bfdb51fc74bc757138b14024b717c5f7492f85264d4bde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
